services:

  backend:
    container_name: backend
    restart: always
    build: images/backend
    command: >
      sh -c "uv run alembic upgrade head
      && cd /app/src/
      && uv run main.py"
    expose:
      - "8000"
    volumes:
      - ./images/backend/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio

  frontend:
    container_name: frontend
    restart: always
    build: images/frontend
    command: >
      sh -c "npm run dev"
    expose:
      - "3000"
    volumes:
      - ./images/frontend/:/app/
    ports:
      - "3000:3000"

  celery_worker:
    container_name: celery_worker
    build: images/backend
    command: >
      sh -c "cd /app/src/
      && uv run celery -A celery_app.celery_app worker --loglevel=info"
    volumes:
      - ./images/backend/:/app/
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always 
    ports:
      - "6379:6379"

  db:
    container_name: db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=pastebin"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
        - db_volume:/var/lib/postgresql/data/

  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_volume:
  minio_data:
