"""Add paste model

Revision ID: 48a2aa71a2ed
Revises:
Create Date: 2025-07-05 11:28:18.382390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a2aa71a2ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pastes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column(
            'expiration',
            sa.Enum(
                'TEN_MINUTES',
                'ONE_HOUR',
                'ONE_DAY',
                'ONE_WEEK',
                'ONE_MONTH',
                'ONE_YEAR',
                'NEVER',
                'BURN_AFTER_READ',
                name='expirationoption',
            ),
            nullable=False,
        ),
        sa.Column(
            'exposure',
            sa.Enum('PUBLIC', 'UNLISTED', name='exposureoption'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastes')
    # ### end Alembic commands ###
