"""Add paste model

Revision ID: da8895869b58
Revises:
Create Date: 2025-07-02 00:49:04.157224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8895869b58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pastes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column(
            'expiration',
            sa.Enum(
                'TEN_MINUTES',
                'ONE_HOUR',
                'ONE_DAY',
                'ONE_WEEK',
                'TWO_WEEKS',
                'ONE_MONTH',
                'SIX_MONTHS',
                'ONE_YEAR',
                'NEVER',
                'BURN_AFTER_READ',
                name='expirationoption',
            ),
            nullable=False,
        ),
        sa.Column(
            'exposure',
            sa.Enum('PUBLIC', 'PRIVATE', 'UNLISTED', name='exposureoption'),
            nullable=False,
        ),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastes')
    # ### end Alembic commands ###
